### ISSUE TITLE
MS SQL Server database service 

### ISSUE THREAD

**Issue by MicheleFietta** [radzenhq/radzen-blazor-studio#49]
While trying to issue the connection to a MS SQL Server database I'm receiving this error message:

-------------------------------------------------------------------------------------------------------------------------------------------
The metadata could not be determined because statement 'REVERT;' in procedure 'sp_helpdiagrams' does not support metadata discovery.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader()
   at Radzen.Server.StoredProcedures.GetStoredProcedureResult(SqlConnection connection, String schema, String name) in /Users/korchev/github/radzen-next/Radzen.Server/DatabaseService.cs:line 739
   at Radzen.Server.StoredProcedures.GetStoredProcedures(String connectionString) in /Users/korchev/github/radzen-next/Radzen.Server/DatabaseService.cs:line 679
   at Radzen.Server.DatabaseService.Infer(InferDatabaseRequest request) in /Users/korchev/github/radzen-next/Radzen.Server/DatabaseService.cs:line 149
ClientConnectionId:5ee1c7c3-ddf2-4975-91e4-422d64742bec
Error Number:11528,State:1,Class:16 
-----------------------------------------------------------------------------------------------------------------------------------------------
Note, I need to have just the tables and views. Fetching the same DB with Radzen Studio no errors occur because I have the chanche to select just tables and views before start fetching and this is very useful in the case of DB not allowing metadata discovery.

**Comment by joshbooker** [comment]
Getting same error on DBs with diagramming enabled.  Also same errors with DBs having sprocs with EXEC.  Agree it would be nice to if the tool would get object metadata **after** selecting objects so we could proceed without modifying DBs by excluding infer of objects that don't behave.  Even better would be to handle the infer error and list the object as not inferrable so we see what's unavailable in RBS during object selection.  Thanks for listening.

**Comment by joshbooker** [comment]
FWIW, Looks like there are at least 25 circumstances where such an error could occur:
| Error | Severity | Event Logged | Description                                                                                                                                                                                     |
|-------|----------|--------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 11509 | 16       | No           | The metadata could not be determined because the statement '%.*ls' is not compatible with the statement '%.*ls'.                                                                                |
| 11510 | 16       | No           | The metadata could not be determined because the statement '%.*ls' in the main batch is not compatible with the statement '%.*ls' in procedure '%.*ls'.                                         |
| 11511 | 16       | No           | The metadata could not be determined because the statement '%.*ls' in procedure '%.*ls' is not compatible with the statement '%.*ls' in the main batch.                                         |
| 11512 | 16       | No           | The metadata could not be determined because the statement '%.*ls' in procedure '%.*ls' is not compatible with the statement '%.*ls' in procedure '%.*ls'.                                      |
| 11513 | 16       | No           | The metadata could not be determined because statement '%.*ls' contains dynamic SQL.  Consider using the WITH RESULT SETS clause to explicitly describe the result set.                         |
| 11514 | 16       | No           | The metadata could not be determined because statement '%.*ls' in procedure '%.*ls'  contains dynamic SQL.  Consider using the WITH RESULT SETS clause to explicitly describe the result set.   |
| 11515 | 16       | No           | The metadata could not be determined because statement '%.*ls' invokes a CLR procedure.  Consider using the WITH RESULT SETS clause to explicitly describe the result set.                      |
| 11516 | 16       | No           | The metadata could not be determined because statement '%.*ls' in procedure '%.*ls' invokes a CLR procedure.  Consider using the WITH RESULT SETS clause to explicitly describe the result set. |
| 11517 | 16       | No           | The metadata could not be determined because statement '%.*ls' invokes a CLR trigger.                                                                                                           |
| 11518 | 16       | No           | The metadata could not be determined because statement '%.*ls' in procedure '%.*ls' invokes a CLR trigger.                                                                                      |
| 11519 | 16       | No           | The metadata could not be determined because statement '%.*ls' invokes an extended stored procedure.                                                                                            |
| 11520 | 16       | No           | The metadata could not be determined because statement '%.*ls' in procedure '%.*ls' invokes an extended stored procedure.                                                                       |
| 11521 | 16       | No           | The metadata could not be determined because statement '%.*ls' uses an undeclared parameter in a context that affects its metadata.                                                             |
| 11522 | 16       | No           | The metadata could not be determined because statement '%.*ls' in procedure '%.*ls' uses an undeclared parameter in a context that affects its metadata.                                        |
| 11523 | 16       | No           | The metadata could not be determined because statement '%.*ls' causes indirect recursion.                                                                                                       |
| 11524 | 16       | No           | The metadata could not be determined because statement '%.*ls' in procedure '%.*ls' causes indirect recursion.                                                                                  |
| 11525 | 16       | No           | The metadata could not be determined because statement '%.*ls' uses a temp table.  Metadata discovery only supports temp tables when analyzing a single-statement batch.                        |
| 11526 | 16       | No           | The metadata could not be determined because statement '%.*ls' in procedure '%.*ls' uses a temp table.                                                                                          |
| 11527 | 16       | No           | The metadata could not be determined because statement '%.*ls' does not support metadata discovery.                                                                                             |
| 11528 | 16       | No           | The metadata could not be determined because statement '%.*ls' in procedure '%.*ls' does not support metadata discovery.                                                                        |
| 11529 | 16       | No           | The metadata could not be determined because every code path results in an error; see previous errors for some of these.                                                                        |
| 11530 | 16       | No           | The metadata could not be determined because there are no code paths that reach the end of the batch.                                                                                           |
| 11550 | 16       | No           | The metadata could not be determined because remote metadata discovery failed for statement '%.*ls'.                                                                                            |
| 11551 | 16       | No           | The metadata could not be determined because remote metadata discovery failed for statement '%.*ls' in procedure '%.*ls'.                                                                       |

**Comment by akorchev** [comment]
We will try to handle that case better in the next version of RBS.

**Comment by akorchev** [comment]
Please try the latest version (alpha.4) it should handle this case.

**Comment by joshbooker** [comment]
Infers without error.  Thanks!  

Radzen Blazor Studio is really nice!  Keep up the great work!
